# docker-compose up -d (muss im Folder dieser datei sein und die datei muss docker-compose.yaml heißen)
version: '3'
services:
  sqlserver:
    image: elsa-db
    build:
      dockerfile: database/docker/Dockerfile
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_PLUGINS=tinymce
      - ADMINER_DESIGN=flat
      - ADMINER_DEFAULT_SERVER=sqlserver