# docker-compose up -d (muss im Folder dieser datei sein und die datei muss docker-compose.yaml heißen)
version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pass@word1
    ports: 
      - 1433:1433
    volumes:
      - mssqldata:/var/opt/mssql
  adminer:
    image: knom/adminer-mssql
    ports:
      - 8080:8080
    environment:
       - ADMINER_PLUGINS=tinymce
       - ADMINER_DESIGN=flat
       - ADMINER_DEFAULT_SERVER=sqlserver
#  rabbitmq:
#    image: rabbitmq
#    ports:
#      - 5672:5672
volumes:
    mssqldata: