/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Elsa.SKS.Package.Services.DTOs
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class WebhookMessage : TrackingInformation
    { 
        /// <summary>
        /// Gets or Sets TrackingId
        /// </summary>
        [RegularExpression("/^[A-Z0-9]{9}$/")]
        [DataMember(Name="trackingId")]
        public string TrackingId { get; set; }
        
    }
}
