/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using Elsa.SKS.Attributes;
using Elsa.SKS.Backend.BusinessLogic.Exceptions;
using Elsa.SKS.Backend.BusinessLogic.Interfaces;
using Elsa.SKS.Backend.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Swashbuckle.AspNetCore.Annotations;

namespace Elsa.SKS.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class LogisticsPartnerApiController : ControllerBase
    {
        private readonly IParcelRegistrationLogic _parcelRegistrationLogic;

        private readonly IMapper _mapper;
        
        private readonly ILogger<LogisticsPartnerApiController> _logger;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="parcelRegistrationLogic"></param>
        /// <param name="mapper"></param>
        /// <param name="logger"></param>
        public LogisticsPartnerApiController(IParcelRegistrationLogic parcelRegistrationLogic, IMapper mapper, ILogger<LogisticsPartnerApiController> logger)
        {
            _parcelRegistrationLogic = parcelRegistrationLogic;
            _mapper = mapper;
            _logger = logger;
        }
        
        /// <summary>
        /// Transfer an existing parcel into the system from the service of a logistics partner. 
        /// </summary>
        /// <param name="body"></param>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <response code="200">Successfully transitioned the parcel</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="409">A parcel with the specified trackingID is already in the system.</response>
        [HttpPost]
        [Route("/parcel/{trackingId}")]
        [ValidateModelState]
        [SwaggerOperation("TransitionParcel")]
        [SwaggerResponse(statusCode: 200, type: typeof(NewParcelInfo), description: "Successfully transitioned the parcel")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "The operation failed due to an error.")]
        public IActionResult TransitionParcel(
            [FromBody] Parcel body, 
            [FromRoute][Required][RegularExpression("^[A-Z0-9]{9}$")] string trackingId)
        {
            try
            {
                var entity = _mapper.Map<Elsa.SKS.Backend.BusinessLogic.Entities.Parcel>(body);
                var parcelEntity = _parcelRegistrationLogic.TransitionParcel(entity, trackingId);
                var result = _mapper.Map<TrackingInformation>(parcelEntity);
                _logger.LogInformation("Transition parcel response: OK");
                return Ok(result);
            }
            catch (TransferException ex)
            {
                _logger.LogInformation(ex, "A parcel with the specified trackingID is already in the system");
                return Conflict();
            }
            catch (BusinessException ex)
            {
                _logger.LogError(ex, "Transition parcel error");
                var error = new Error {ErrorMessage = ex.Message};
                return BadRequest(error);
            }
        }
    }
}
