/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using AutoMapper;
using Elsa.SKS.Attributes;
using Elsa.SKS.Backend.BusinessLogic.Exceptions;
using Elsa.SKS.Backend.BusinessLogic.Interfaces;
using Elsa.SKS.Backend.Services.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Swashbuckle.AspNetCore.Annotations;

namespace Elsa.SKS.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SenderApiController : ControllerBase
    {
        private readonly IParcelRegistrationLogic _parcelRegistrationLogic;
        
        private readonly IMapper _mapper;
        
        private readonly ILogger<SenderApiController> _logger;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="parcelRegistrationLogic"></param>
        /// <param name="mapper"></param>
        /// <param name="logger"></param>
        public SenderApiController(IParcelRegistrationLogic parcelRegistrationLogic, IMapper mapper, ILogger<SenderApiController> logger)
        {
            _parcelRegistrationLogic = parcelRegistrationLogic;
            _mapper = mapper;
            _logger = logger;
        }
        
        /// <summary>
        /// Submit a new parcel to the logistics service. 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="201">Successfully submitted the new parcel</response>
        /// <response code="400">The operation failed due to an error.</response>
        [HttpPost]
        [Route("/parcel")]
        [ValidateModelState]
        [SwaggerOperation("SubmitParcel")]
        [SwaggerResponse(statusCode: 201, type: typeof(NewParcelInfo), description: "Successfully submitted the new parcel")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "The operation failed due to an error.")]
        public IActionResult SubmitParcel([FromBody] Parcel body)
        {
            try
            {
                var entity = _mapper.Map<Elsa.SKS.Backend.BusinessLogic.Entities.Parcel>(body);
                var parcel = _parcelRegistrationLogic.SubmitParcel(entity);
                var newParcelInfo = _mapper.Map<NewParcelInfo>(parcel);
                _logger.LogInformation("Submit parcel response: Created");
                return Created("/" + newParcelInfo.TrackingId, newParcelInfo);
            }
            catch (BusinessException ex)
            {
                _logger.LogError(ex, "Submit parcel error");
                var error = new Error { ErrorMessage = ex.Message };
                return BadRequest(error);
            }
        }
    }
}
